# Generated by Django 5.1.7 on 2025-03-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('guest_count', models.PositiveIntegerField()),
            ],
        ),
    ]
