# Generated by Django 5.1.7 on 2025-03-26 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AgentApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sid',
            fields=[
                ('phone_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('callsid', models.CharField(max_length=40)),
            ],
        ),
    ]
